# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/NexysVideo.xdc

# IP: ip/MULT_44X16/MULT_44X16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MULT_44X16 || ORIG_REF_NAME==MULT_44X16}]

# IP: ip/RAM1MIN/RAM1MIN.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM1MIN || ORIG_REF_NAME==RAM1MIN}]

# IP: ip/S2_ROM_17X400/S2_ROM_17X400.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S2_ROM_17X400 || ORIG_REF_NAME==S2_ROM_17X400}]

# IP: ip/S1_ROM_17X400/S1_ROM_17X400.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==S1_ROM_17X400 || ORIG_REF_NAME==S1_ROM_17X400}]

# IP: ip/RAM_44X400_WF/RAM_44X400_WF.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_44X400_WF || ORIG_REF_NAME==RAM_44X400_WF}]

# IP: ip/RAM_25X400_DP/RAM_25X400_DP.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_25X400_DP || ORIG_REF_NAME==RAM_25X400_DP}]

# IP: ip/RAM_16X400_WF/RAM_16X400_WF.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_16X400_WF || ORIG_REF_NAME==RAM_16X400_WF}]

# IP: ip/MACC_FILTER/MACC_FILTER.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MACC_FILTER || ORIG_REF_NAME==MACC_FILTER}]

# IP: ip/MACC/MACC.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MACC || ORIG_REF_NAME==MACC}]

# IP: ip/ADD_SUB/ADD_SUB.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD_SUB || ORIG_REF_NAME==ADD_SUB}]

# IP: ip/ROM_X/ROM_X.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_X || ORIG_REF_NAME==ROM_X}]

# IP: ip/ROM_ERROR1/ROM_ERROR1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_ERROR1 || ORIG_REF_NAME==ROM_ERROR1}]

# IP: ip/ROM_ERROR2/ROM_ERROR2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_ERROR2 || ORIG_REF_NAME==ROM_ERROR2}]

# XDC: ip/RAM1MIN/RAM1MIN_ooc.xdc

# XDC: ip/S2_ROM_17X400/S2_ROM_17X400_ooc.xdc

# XDC: ip/S1_ROM_17X400/S1_ROM_17X400_ooc.xdc

# XDC: ip/RAM_44X400_WF/RAM_44X400_WF_ooc.xdc

# XDC: ip/RAM_25X400_DP/RAM_25X400_DP_ooc.xdc

# XDC: ip/RAM_16X400_WF/RAM_16X400_WF_ooc.xdc

# XDC: ip/ROM_X/ROM_X_ooc.xdc

# XDC: ip/ROM_ERROR1/ROM_ERROR1_ooc.xdc

# XDC: ip/ROM_ERROR2/ROM_ERROR2_ooc.xdc
